### ISSUE TITLE
catkin_make error on thread.cpp

### ISSUE THREAD

**Issue by Raffa87** [iirob/ros_opcua_communication#18]
Hi!
I am using catkin_make on ros kinetic (ubuntu 18.04) and I am getting an error when compiling using catkin_make: 

ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/include/opc/common/thread.h:31:16: error: ‘function’ in namespace ‘std’ does not name a template type
   typedef std::function<void()> ThreadProc;

**Comment by jannho** [comment]
I had the same issue, checkout to master branch for freeopcua and build again.

**Comment by destogl** [comment]
Did it work?

**Comment by Ozzy94** [comment]
ive tried that, it solves some issues but stil got one left reed below: im on ubuntu 18.04 and ros Melodic
[ 69%] Building CXX object ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/CMakeFiles/opcuaclient.dir/src/client/client.cpp.o
/home/ozzy/ws_2/src/ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/src/client/client.cpp:30:10: fatal error: mbedtls/entropy.h: No such file or directory
 #include <mbedtls/entropy.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/CMakeFiles/opcuaclient.dir/build.make:134: recipe for target 'ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/CMakeFiles/opcuaclient.dir/src/client/client.cpp.o' failed
make[2]: *** [ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/CMakeFiles/opcuaclient.dir/src/client/client.cpp.o] Error 1
CMakeFiles/Makefile2:2578: recipe for target 'ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/CMakeFiles/opcuaclient.dir/all' failed
make[1]: *** [ros_opcua_communication/ros_opcua_impl_freeopcua/freeopcua/CMakeFiles/opcuaclient.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by destogl** [comment]
Do you need c++ version? Or would be also happy with python interface?

**Comment by Ozzy94** [comment]
well i have the python running so that works, i just deleted the freeopcua part and compiled.
but id like to use the C++ variant rather than python.

**Comment by hambabumba** [comment]
Hey
I had the same problem. (Ubuntu 18.04 and ros Melodic)
I changed a few lines in code to solve it. It solved the error messages.
+++++++++++
-I added to the file "freeopcua/include/opc/common/thread.h"
-> #include \<functional> 
because of: error: ‘function’ in namespace ‘std’ does not name a template type

-to the file "freeopcua/src/server/address_space_internal.h"
-> #include \<iostream>
because of:error: ‘cout’ is not a member of ‘std’

-and to the file "freeopcua/src/server/server_object.h"
-> #include \<iostream>
because of:
-error: ‘clog’ is not a member of ‘std’
-error: ‘cerr’ is not a member of ‘std’
++++++++++++

Not sure yet, if I broke anything. Now I will check if it works

Edit: It works (probably)

**Comment by destogl** [comment]
@hambabumba thanks!

Plese tell us if it works :)

**Comment by hambabumba** [comment]
Nothing I tried broke because of the changes, so I think it works. 
But I couldn't test it perfectly, because I neither understand OPC UA nor ROS, so I only tested some example files.

**Comment by Meyyarparthiban** [comment]
@hambabumba hi, i am having the same error during the build. So i am following your instruction but i am not able to understand what we supposed to include? 
quote example:
"-I added to the file "freeopcua/include/opc/common/thread.h"
**-> #include**
because of: error: ‘function’ in namespace ‘std’ does not name a template type"

so can i know what needs to be included or am i reading the solution wrongly? thanks so much for your assistance.

**Comment by Meyyarparthiban** [comment]
@hambabumba  i have added the supposed file to the thread.cpp, but i am still having the same error regarding the thread.h.

when i open the thread.cpp file, it seems like there is already a thread.h file included. do we replace it or something?

thanks a lot for the solution guys!
![Screenshot from 2020-06-01 19-54-46](https://user-images.githubusercontent.com/65347148/83438510-d3b67100-a441-11ea-98f7-5daed25ea40f.png)

**Comment by hambabumba** [comment]
> 
> 
> @hambabumba hi, i am having the same error during the build. So i am following your instruction but i am not able to understand what we supposed to include?
> quote example:
> "-I added to the file "freeopcua/include/opc/common/thread.h"
> **-> #include**
> because of: error: ‘function’ in namespace ‘std’ does not name a template type"
> 
> so can i know what needs to be included or am i reading the solution wrongly? thanks so much for your assistance.

sorry for the late reply. I hope you have solved it already. I fixed my comment earlier, I hadn't noticed that the header files were missing. I didn't know that you had to write ' \\'  before '<...>' or else nothing is showing. 

Is everything fine? or is something unclear after the edit?

**Comment by Meyyarparthiban** [comment]
hi @hambabumba ,

thanks a lot for your reply and edit! i actually managed to search on the internet for the same solution that you suggested, All the issues with \<iostream> dissapeared but im still having issue with the function part despite having added the include\<functional> in the thread.cpp. 

i searched further and found ppl mentioning that it might be because of compiler version problem , and i have to add in the cmake file a line of code : add_compile_options(-std=c++11)
as mentioned in : https://stackoverflow.com/questions/15048117/c-function-in-namespace-std-does-not-name-a-type/15048131, but it leads to more problem where the build take super long that the process was killed.

so right now im not too sure how to solve the problem, or where the problem comes from haha, but i will try to check again with the include\<functional> solution, perhaps i missed it some where or mis-positioned it.

anyway thanks for the reply and if i get to see whats my problem i will update here again.

**Comment by destogl** [comment]
This should be solved in #22 

I manage to compile and execute the examples on ROS melodic.
